# Generated by Django 3.1.3 on 2020-11-28 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('body', models.CharField(blank=True, max_length=160)),
                ('views_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
